---

- name: Ensure nginx is installed
  apt:
    name: nginx
    state: latest

- name: Copy nginx.conf file
  copy:
    src: nginx.conf
    dest: /etc/nginx
    owner: root
    group: root
    mode: "0644"
  notify:
    - reload nginx

- name: Ensure directories exist
  file:
    path: "{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: "0400"
  with_items:
    - /etc/nginx/ssl

- name: Remove default files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/sites-available/default

- name: Ensure nginx is started
  service:
    name: nginx
    state: started
